#677: Added back settings for version first_frame, last_frame.
mbrainerd/tk-multi-reviewsubmission pull request #6
Opened 2018-05-14 12:16 UTC by aparna-d2

2018-05-14 12:21 UTC, aparna-d2 commented on app.py
> +        return mov_first_frame, mov_last_frame
This logic is not bulletproof, but it is the best I have, because there is no way to predict what will happen in the subprocess through code.

2018-05-23 00:06 UTC, mbrainerd commented on app.py
> +        return mov_first_frame, mov_last_frame
I still don't understand why this logic is here. I really feel like this needs to be in the calling code, not in tk-multi-reviewsubmission.

2018-05-23 00:06 UTC, mbrainerd requested changes
See inline note

2018-05-24 08:30 UTC, aparna-d2 commented on app.py
> +        return mov_first_frame, mov_last_frame
I put this here because this is only used to update a field on the version entity, not to actually shoot the movie.

2018-05-24 08:31 UTC, aparna-d2 commented
Closing because comp is now required to render the black frames for delivery, removing the necessity for this.

2018-05-24 19:15 UTC, mbrainerd commented
Reopening...don't we still need to reenable the attribute setting for sg_first_frame and sg_last_frame?

2018-07-02 18:58 UTC, mbrainerd commented
Closing as this is now being handled in #9

2018-07-02 18:58 UTC, closed without merging